### ISSUE TITLE
Vue Component Template Hot Reload

### ISSUE THREAD

**Issue by oedemis** [gwtboot/gwt-boot-samples#10]
Why can the changes not hot reload if i change the code in html template files ?

**Comment by lofidewanto** [comment]
Did you try to reload the "Jetty" web server from the Swing UI? Because it is HTML and not JavaScript...

**Comment by oedemis** [comment]
yes it is not working

**Comment by lofidewanto** [comment]
I tested following:

- Change [index.html](https://github.com/gwtboot/gwt-boot-samples/blob/master/gwt-boot-sample-ui-vue-gwt/src/main/java/com/github/gwtboot/sample/ui/vuegwt/public/index.html): refresh works after reload the web browser 2 times.
- Change [CounterComponent.html:](https://github.com/gwtboot/gwt-boot-samples/blob/master/gwt-boot-sample-ui-vue-gwt/src/main/java/com/github/gwtboot/sample/ui/vuegwt/client/components/counter/CounterComponent.html) refresh does not work at all. I need to do mvn clean to see my changes.

**Comment by lofidewanto** [comment]
In the mean time I asked the VueGWT discussion: https://gitter.im/VueGWT/vue-gwt

I'll inform you when I get the answer.

**Comment by lofidewanto** [comment]
CounterComponent.html --> from this file you will need to generate the Java files. Afterwards the Java files should be transpiled to JavaScript files. For this purpose we need to activate the APT generator.

**Comment by lofidewanto** [comment]
In the meantime I got an answer:
- javac compiler apt only recognizes Java files and not HTML files therefore it won't regenerate the Java files from the HTML files.
- Another solutions is to use extension of your IDE and here is how: https://vuegwt.github.io/vue-gwt/guide/project-setup.html#configure-your-ide

Over there you can use VueGWT plugin for IntelliJ or Eclipse which could notice if you change your HTML files and regenerate the Java files.

**Comment by lofidewanto** [comment]
That's it, hope it helps you...
