### ISSUE TITLE
serve public assets issues

### ISSUE THREAD

**Issue by oedemis** [gwtboot/gwt-boot-samples#19]
With following setup with img folder in public folder
src/main/java/public/img

when i want to serve the image with elemtal2 style widget rendering in frontend like component.attr("src", "/app/img/testimage/" it not renders the image why ? ist this a general issue with project structure ?

**Comment by lofidewanto** [comment]
Hmm I think you need to know the "end" structure of your JS. Remember at the end you have JS and not Java with its structure...

Check out my presentation: https://bit.ly/gwtintropresentation -- Page 29 where you can see the structure of the JS result. So I always look at the "target" result...

Hope this helps...

**Comment by oedemis** [comment]
@lofidewanto thanks
another point is how we can change the url to / instead of renamed path in module.gwt.xml

**Comment by lofidewanto** [comment]
Did you try with "/" in the Maven plugin of GWT? Something like this?

`
          <plugin>
            <groupId>net.ltgt.gwt.maven</groupId>
            <artifactId>gwt-maven-plugin</artifactId>
            <configuration>
               <moduleName>hello.YourModule</moduleName>
               <startupUrls>
                  <url>/</url>
               </startupUrls>
            </configuration>
         </plugin>
`

**Comment by lofidewanto** [comment]
Closed.
