### ISSUE TITLE
Outdated Vue example

### ISSUE THREAD

**Issue by baldram** [gwtboot/gwt-boot-samples#5]
Hello @adrienbaron ! 

It's an interesting project which helps to start with GWT and chosen frontend framework quickly. 
I had a look on Vue which seems to be an interesting option.
I see that the example seems to be outdated regarding to the latest Vue-GWT release.

Please see:
https://github.com/gwtboot/gwt-boot-samples/blob/master/gwt-boot-sample-ui-vue-gwt/src/main/java/com/github/gwtboot/sample/ui/vuegwt/client/components/counter/CounterComponent.java

And this:
https://axellience.github.io/vue-gwt-demo/

Now it's enough to use `@Data` annotation instead of JsInterop related one.

```
@Component
public class CounterComponent implements IsVueComponent {
    @Data int counterValue = 0;
}
```
The latest Vue-gwt release delivers a lot of groundbreaking changes. Gwtboot is probably not yet adjusted.

Thanks and best regards,
Marcin

**Comment by adrienbaron** [comment]
@baldram Just pushed the updated sample and upgraded the dependency in GWT Boot Modules project, I'm not sure if the SNAPSHOT of modules gets published automatically or if @lofidewanto has to do something for it to get published though.
If you have questions regarding Vue GWT, we have an active Gitter channel: https://gitter.im/Axellience/vue-gwt

**Comment by lofidewanto** [comment]
I'll deploy the change to SNAPSHOT repo... Wait a bit.

**Comment by lofidewanto** [comment]
@adrienbaron: I did not see your changes, did you merge to Master?

**Comment by lofidewanto** [comment]
Done, the new dependencies for gwtboot-modules is on the SNAPSHOT repo OSS Sonatype.

**Comment by baldram** [comment]
Thank you @adrienbaron for fast reaction! 

> I'm actually also one of the main dev of Vue GWT 

Yes, I know that ;-) That's why I mentioned you in the header :-)

Thank you @lofidewanto for support!
